### ISSUE TITLE
ionAutocompleteController.itemsMethod is not a function (but I set the items-method attribute).

### ISSUE THREAD

**Issue by tapsaid** [guylabs/ion-autocomplete#69]
I'm unable to get the items for completion (the goal of this project by the way). So, I tried to find out the problem and it turned up to me that the following check failed : 
<code>
scope.$watch('viewModel.searchQuery', function (query) {

                    // right away return if the query is undefined to not call the items method for nothing
                    if (query === undefined) {
                        return;
                    } 

                    // if the search query is empty, clear the items
                    if (query == '') {
                        ionAutocompleteController.items = [];
                    }

                    if (angular.isFunction(ionAutocompleteController.itemsMethod)) {
                     // NEVER REACHED BLOCK 
                    }

</code>

**Comment by guylabs** [comment]
Hi,

could you please provide an example on how you configure your component and how the `items-method` looks like on your side? You can always have a look at the CodePen demo for reference. And which check is failing?

Thanks and regards,

Guy

**Comment by deadalusai** [comment]
The codepen appears to be broken as well.

Downgrading to commit [9a74e4e87](https://github.com/guylabs/ion-autocomplete/commit/9a74e4e87a80b6d8e9742f59e59aec023d3123d0) seems to fix the problem: http://codepen.io/anon/pen/yYYLdE

**Comment by deadalusai** [comment]
It looks like `bindToController` doesn't work in Ionic 1.0.0? Updating the Ionic version to 1.1.0 [in the codepen](http://codepen.io/anon/pen/qOOEOB) seems to fix the issue.

**Comment by guylabs** [comment]
Hi Benjamin,

I just fixed the codepen: http://codepen.io/guylabs/pen/GJmwMw

Thanks for pointing this out!

Regards,

Guy

**Comment by tapsaid** [comment]
Thanks for the reply even though I managed to implement a quick search (using angular filter: searchText as result) as a workaround.
The latest block where I wrote "NEVER REACHED BLOCK" is the failing one.
I will try to use your codepen ASAP and will let you know.

Keep up the good work.

Regards,

Seydou.

**Comment by cannahum** [comment]
Hi there,

I have the same issue. I'm using ionic 1.1.0, ion-autocomplete 0.3.0 and I wasn't able to get any results when I type in a query. I was also able to track the problem down to the same spot:

if (angular.isFunction(ionAutocompleteController.itemsMethod)) {
//this predicate fails without exception. I tried to print ionAutoCompleteController object and I didn't find my items-method in there. I also didn't find my prepopulated items either. Here's how I use the directive:


<input ion-autocomplete 
      ng-model="data.post_tags"
      type="text" readonly="readonly" class="ion-autocomplete"
      search-items="autoComplete.prePopulatedTags"
      autocomplete="off"
      items-method="autoComplete.searchTags(query)"
      items-method-value-key="result"
      select-items-label="Try These:"
      selected-items-label="Current Tags:"
      placeholder="Enter tags ..." 
      items-clicked-method="autoComplete.itemsClicked(callback)"/>

This whole thing was working beautifully before the updates, and I really appreciate your work. It would be awesome if we could fix this! 

Best,
Jon

**Comment by guylabs** [comment]
Hi Jon,

could you please try it with the master and not with version `0.3.0` ? There are some changes on the master and I will release `0.3.1` shortly when all the issues are fixed. 

Thanks and regards,

Guy

**Comment by cannahum** [comment]
Guy,

I tried the master repo from github, same issue. I was actually working in parallel with your demo, so I actually tried the exact demo by embedding it in my app, but I'm getting the same issue. In order to test it a little more, I did the following:

<input ion-autocomplete 
      ng-model="data.post_tags"
      type="text" readonly="readonly" class="ion-autocomplete"
      search-items="autoComplete.prePopulatedTags"
      items-method="autoComplete.searchTags(query)"
      items-method-value-key="autoComplete.itemsMethodValueKey"
      select-items-label="autoComplete.selectItemsLabel"
      selected-items-label="autoComplete.selectedItemsLabel"
      placeholder="autoComplete.placeholder" 
      items-clicked-method="autoComplete.itemsClicked(callback)"
      cancel-button-clicked-method="autoComplete.cancelButtonClickedMethod(callback)"/>

Then I went into the ion-autocomplete.js to print out what values were being passed into the ionAutoCompleteController. It seems, the binding isn't working well, all I'm getting is the hard-coded "autoComplete.placeholder" instead of the value of that variable. 

For itemsMethod specifically, I tried this in the directive:
items-method="{{autoComplete.searchTags(query)}}", in which case it went into an infinite loop.

I'm just trying to report everything I spot. Please let me know if these don't make sense to you.

Best,
Jon

P.S. - when I used the same repo as the demo (rawgit.com/guylabs/...) I got the same results, so I think that repo is the same as the Master in github.

**Comment by guylabs** [comment]
Hi @cannahum,

the strange thing is that I never had this issue with the `items-method` so could you maybe create a codepen where I can reproduce the issue? And please also have a look at the `*html` files here as these are used for the end to end tests: https://github.com/guylabs/ion-autocomplete/tree/master/test/e2e

Thanks and sorry for the late response,

Guy

**Comment by guylabs** [comment]
Hi,

any news on this? I need to release `0.3.1` and I want to close these issues.

Thanks and regards,

Guy

**Comment by cannahum** [comment]
All good on my end, I had a hard time updating to Ionic 1.1.0 persistently (for some reason it rolled back). It works now, I still need to test my old functions with it, but at least no bugs!

Thanks a ton, for the good work!

**Comment by guylabs** [comment]
Ok great. Then I will close the issue and if you it still doesn't work for you then please reopen it.

Thanks for the feedback,

Cheers,

Guy

**Comment by edmondchui** [comment]
I just notice that within this block in the code:

https://github.com/guylabs/ion-autocomplete/blob/master/src/ion-autocomplete.js#L40-L48

this line is missing:
```js
                this.itemsMethod = valueOrDefault($parse($attrs.itemsMethod), undefined);
```

After adding this line I don't see the error.

However, I still can't get my ```items-method``` being called.

**Comment by guylabs** [comment]
Hi @edmondchui,

is your query parameter named `query`? Can you maybe create a codepen where the issue is reproducible?

Thanks and regards,

Guy

**Comment by helsont** [comment]
Hi, having this issue at the moment. Copying code straight from the docs.

**Comment by guylabs** [comment]
@helsont Which version of Ionic and `ion-autocomplete` are you using? If you are using Ionic `1.1.0` and `0.3.1` of the `ion-autocomplete` and still have the issue, please create a codepen which shows this error. Please also check out the sample html files here as these are running properly: https://github.com/guylabs/ion-autocomplete/tree/master/test/e2e

Thanks and regards,

Guy

**Comment by helsont** [comment]
Hi @guylabs,

Thanks so much for the speedy response. I ended up spending the last hour upgrading my ionic files and everything's working perfectly. Great job with the plugin! Exactly what I needed.

Helson

**Comment by guylabs** [comment]
Hi Helson,

cool that it works now ;).

Regards,

Guy

**Comment by edmondchui** [comment]
@guylabs Sorry for the late reply. My issue was resolved automatically after I upgrade angularJS from 1.3.15 to 1.4.8. Thanks.

**Comment by fotoflo** [comment]
Hi there, I'm using Ionic 1.7.12 with the code from your codepen and getting "Uncaught TypeError: ionAutocompleteController.itemsMethod is not a function" -- any suggestions?

**Comment by guylabs** [comment]
Hi,

**Comment by guylabs** [comment]
Hi,

sorry for my late reply but I was in vacations. @edmondchui cool that you got it running. @fotoflo there is no Ionic `1.7.12` version. Are you using any other project/wrapper of Ionic? The latest version is `1.2.4` and this is currently not supported. The latest Ionic version supported is `1.1.1` as you can see here: https://github.com/guylabs/ion-autocomplete#ionic-compatibility. Could you please try to use these versions of Ionic? 

I will try to update the component to use the latest Ionic version.

Thanks and regards,

Guy

**Comment by MrRobWad** [comment]
running `$ ionic lib update` resolved this issue for me. Essentially, I updated bower.json ionic package from version driftyco/ionic-bower#1.0.1 to driftyco/ionic-bower#1.3.0.
